// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMonTpXVFIpes8BH-fK8QufGdsD1mZCg4',
    appId: '1:25662583767:web:ced8e1f3d79313a3eb5192',
    messagingSenderId: '25662583767',
    projectId: 'voting_app-2f27c',
    authDomain: 'voting_app-2f27c.firebase_option.com',
    storageBucket: 'voting_app-2f27c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ZqOwjRkL96_wqG71W5_aUVr_B6EjBSk',
    appId: '1:25662583767:android:e7c7c9eacc26e256eb5192',
    messagingSenderId: '25662583767',
    projectId: 'votingapp-2f27c',
    storageBucket: 'votingapp-2f27c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAq6qcRR58zzTH4AwFo6oLOaRUA2pQSLg',
    appId: '1:25662583767:ios:8e9b0328ae521cc7eb5192',
    messagingSenderId: '25662583767',
    projectId: 'voting_app-2f27c',
    storageBucket: 'voting_app-2f27c.firebase_options.app',
    androidClientId: '25662583767-s5f60esld95mp45gpm6d9s1u1vrqbrea.apps.googleusercontent.com',
    iosClientId: '25662583767-0lcnj1nqaie08luidoeht6buurm6gp6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.new_pro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAq6qcRR58zzTH4AwFo6oLOaRUA2pQSLg',
    appId: '1:25662583767:ios:8e9b0328ae521cc7eb5192',
    messagingSenderId: '25662583767',
    projectId: 'voting_app-2f27c',
    storageBucket: 'voting_app-2f27c.firebasestorage.app',
    androidClientId: '25662583767-s5f60esld95mp45gpm6d9s1u1vrqbrea.apps.googleusercontent.com',
    iosClientId: '25662583767-0lcnj1nqaie08luidoeht6buurm6gp6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMonTpXVFIpes8BH-fK8QufGdsD1mZCg4',
    appId: '1:25662583767:web:e54a9ad84f5a4267eb5192',
    messagingSenderId: '25662583767',
    projectId: 'votingapp-2f27c',
    authDomain: 'votingapp-2f27c.firebaseapp.com',
    storageBucket: 'votingapp-2f27c.firebasestorage.app',
  );

}